name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install raylib
      run: |
        sudo apt instsall -y raylib
    - name: Generate configuration
      run: autoreconf -i
    - name: Generate makefiles
      run: ./configure
    - name: Build
      run: make
