name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download, build and install raylib
      run: |
        sudo apt install -y build-essential
        sudo apt install -y libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
        git clone https://github.com/raysan5/raylib.git raylib
        cd raylib/src
        make PLATFORM=PLATFORM_DESKTOP
        sudo make install
        cp -vv raylib/libraylib.a /usr/lib
    - name: Generate configuration
      run: autoreconf -i
    - name: Generate makefiles
      run: ./configure
    - name: Build
      run: make
